export const EMPTY_PRODUCT = {
    id: '',
    category_id: 0,
    name: '',
    article: '',
    nomenclature: '',
    made_in: '',
    price: 0,
    description: '',
    id_1c: '',
    part_1c: 0,
    active: true,
    image: '',
    resize: 'false',
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    barcode: '',
    min_left: 0,
};
